### ISSUE TITLE
Do mCaller have 5mC model ?

### ISSUE THREAD

**Issue by hygine** [al-mcintyre/mCaller#7]
1. Question1: when I use mCaller call 5mC meth but I haven't 5mC model file, do you have 5mC train model to use ? the code like this : 
`mCaller.py -m GATC  -r  reference.fa  -e human.0.eventalign.tsv -f  astq_0.fastq -b C`
got Error like this: 
```
Traceback (most recent call last):
  File "mCaller.py", line 187, in <module>
    main()
  File "mCaller.py", line 157, in main
    assert os.path.isfile(modelfile), 'model file not found at '+modelfile
AssertionError: model file not found at /software/mCaller/model_NN_6_m5C.pkl

```

2. Question2: dose those model file suit for any species ？

**Comment by al-mcintyre** [comment]
1. We do not currently have a model for m5C. We did release bisulfite sequencing data with the paper and you could use highly methylated positions to train a model if you don't have your own training set. 

2. Models are better suited for predictions at sequence contexts that lead to similar changes in currents as in the training data (ideally, you would use similar contexts for training but this is not always possible), but beyond that, are not species-specific. Figure 3 in our papers shows the application of an E.coli-trained model to data from other bacterial species.
